defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "weekly_events"
    values:
      layout: "weekly_event"

repository: Eddington-Residents-Association/website

collections:
  meetings:
    output: false
  weekly_events:
    output: true
    permalink: /events/:name
    folder: _weekly_events

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
